// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "toggle": {
      name: "toggle",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/toggle.tsx"],
      component: React.lazy(() => import("#registry/default/ui/toggle.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "address-badge": {
      name: "address-badge",
      type: "registry:ui",
      registryDependencies: ["badge","tooltip"],
      files: ["registry/default/components/identity/address-badge.tsx"],
      component: React.lazy(() => import("#registry/default/components/identity/address-badge.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/tooltip.tsx"],
      component: React.lazy(() => import("#registry/default/ui/tooltip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("#registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("#registry/default/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-toast": {
      name: "use-toast",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-toast.ts"],
      component: React.lazy(() => import("#registry/default/hooks/use-toast.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
