// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "address-badge": {
      name: "address-badge",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/identity/address-badge.tsx","registry/default/lib/utils/address.ts"],
      component: React.lazy(() => import("#registry/default/components/identity/address-badge.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/identity/avatar.tsx"],
      component: React.lazy(() => import("#registry/default/components/identity/avatar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "avatar-wagmi": {
      name: "avatar-wagmi",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/identity/avatar-wagmi.tsx"],
      component: React.lazy(() => import("#registry/default/components/identity/avatar-wagmi.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "name": {
      name: "name",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/identity/name.tsx","registry/default/hooks/ens/use-efp-api.ts"],
      component: React.lazy(() => import("#registry/default/components/identity/name.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "name-wagmi": {
      name: "name-wagmi",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/identity/name-wagmi.tsx"],
      component: React.lazy(() => import("#registry/default/components/identity/name-wagmi.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "attestation-card": {
      name: "attestation-card",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/attestations/attestation-card.tsx","registry/default/hooks/eas/use-get-attestation-with-uid.tsx"],
      component: React.lazy(() => import("#registry/default/components/attestations/attestation-card.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "attestations-table": {
      name: "attestations-table",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/components/attestations/attestations-table.tsx","registry/default/components/attestations/attestation-schema-badge.tsx","registry/default/components/data-table.tsx","registry/default/hooks/eas/use-get-attestations.ts","registry/default/lib/eas/easscan.ts","registry/default/lib/utils/hex.ts"],
      component: React.lazy(() => import("#registry/default/components/attestations/attestations-table.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "hex": {
      name: "hex",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils/hex.ts"],
      component: React.lazy(() => import("#registry/default/lib/utils/hex.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "address": {
      name: "address",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils/address.ts"],
      component: React.lazy(() => import("#registry/default/lib/utils/address.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-get-attestation-with-uid": {
      name: "use-get-attestation-with-uid",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/eas/use-get-attestation-with-uid.tsx"],
      component: React.lazy(() => import("#registry/default/hooks/eas/use-get-attestation-with-uid.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
