name: Check

on:
  pull_request:
    branches:
      - 'draft'
      - 'main'
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '9'
  TEST_EAS_PRIVATE_KEY: ${{ secrets.TEST_EAS_PRIVATE_KEY }}
  TEST_USER_PRIVATE_KEY: ${{ secrets.TEST_USER_PRIVATE_KEY }}

jobs:
  check:
    name: Run tests and format checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4

      - name: Fetch base commit
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }} --depth=1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Download package artifacts
        uses: actions/download-artifact@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests - Unit
        run: pnpm --filter ui-react run test:unit

      - name: Run Check
        run: pnpm exec turbo run check

      - name: Report Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { job, conclusion } = context.payload.workflow_run || {};
            if (conclusion === 'failure') {
              core.setFailed('Lint and format checks failed');
            }
