name: Geist Dapp Kit

on:
  pull_request:
    branches:
      - 'draft'
      - 'main'  
  push:
    branches:
      - 'draft'
      - 'main'
    paths:
      - 'apps/storybook/**'
      - 'pnpm-*.yaml'

env:
  NODE_VERSION: '22'
  TEST_EAS_PRIVATE_KEY: ${{ secrets.TEST_EAS_PRIVATE_KEY }}
  TEST_USER_PRIVATE_KEY: ${{ secrets.TEST_USER_PRIVATE_KEY }}
  LIGHTHOUSE_API_KEY: ${{ secrets.LIGHTHOUSE_API_KEY }}

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Download package artifacts
        uses: actions/download-artifact@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm --filter storybook build

      - name: Upload storybook build
        uses: actions/upload-artifact@v3
        with:
          name: storybook-build
          path: apps/storybook/storybook-static

      - name: Build Registry
        run: pnpm --filter ui-react build:registry

      # smoke test, disabled for now
      # - name: Build gql
      #   run:  pnpm --filter graphql build:gql

  deploy-storybook:
    needs: [build-storybook]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Download storybook build
        uses: actions/download-artifact@v4
        with:
          name: storybook-build
          path: apps/storybook/storybook-static

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy app
        env:
          FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
          FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
        run: pnpm --dir apps/storybook deploy:fleek
